/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActividadesRouteImport } from './routes/actividades'
import { Route as ArtistasRouteImport } from './routes/artistas'
import { Route as ComercioRouteImport } from './routes/comercio'
import { Route as FeriaDelMediodiaRouteImport } from './routes/feria-del-mediodia'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as InformacionRouteImport } from './routes/informacion'
import { Route as ObjetosPerdidosRouteImport } from './routes/objetos-perdidos'
import { Route as PregoneraRouteImport } from './routes/pregonera'
import { Route as PrensaRouteImport } from './routes/prensa'
import { Route as ProgramaRouteImport } from './routes/programa'
import { Route as QueVerRouteImport } from './routes/que-ver'
import { Route as RecuerdoRouteImport } from './routes/recuerdo'
import { Route as ReinasRouteImport } from './routes/reinas'
import { Route as SaludaRouteImport } from './routes/saluda'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesRoute = ActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasRoute = ArtistasRouteImport.update({
  id: '/artistas',
  path: '/artistas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercioRoute = ComercioRouteImport.update({
  id: '/comercio',
  path: '/comercio',
  getParentRoute: () => rootRouteImport,
} as any)
const FeriaDelMediodiaRoute = FeriaDelMediodiaRouteImport.update({
  id: '/feria-del-mediodia',
  path: '/feria-del-mediodia',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const InformacionRoute = InformacionRouteImport.update({
  id: '/informacion',
  path: '/informacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetosPerdidosRoute = ObjetosPerdidosRouteImport.update({
  id: '/objetos-perdidos',
  path: '/objetos-perdidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PregoneraRoute = PregoneraRouteImport.update({
  id: '/pregonera',
  path: '/pregonera',
  getParentRoute: () => rootRouteImport,
} as any)
const PrensaRoute = PrensaRouteImport.update({
  id: '/prensa',
  path: '/prensa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramaRoute = ProgramaRouteImport.update({
  id: '/programa',
  path: '/programa',
  getParentRoute: () => rootRouteImport,
} as any)
const QueVerRoute = QueVerRouteImport.update({
  id: '/que-ver',
  path: '/que-ver',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuerdoRoute = RecuerdoRouteImport.update({
  id: '/recuerdo',
  path: '/recuerdo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinasRoute = ReinasRouteImport.update({
  id: '/reinas',
  path: '/reinas',
  getParentRoute: () => rootRouteImport,
} as any)
const SaludaRoute = SaludaRouteImport.update({
  id: '/saluda',
  path: '/saluda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/artistas': typeof ArtistasRoute
  '/comercio': typeof ComercioRoute
  '/feria-del-mediodia': typeof FeriaDelMediodiaRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
  '/informacion': typeof InformacionRoute
  '/objetos-perdidos': typeof ObjetosPerdidosRoute
  '/pregonera': typeof PregoneraRoute
  '/prensa': typeof PrensaRoute
  '/programa': typeof ProgramaRoute
  '/que-ver': typeof QueVerRoute
  '/recuerdo': typeof RecuerdoRoute
  '/reinas': typeof ReinasRoute
  '/saluda': typeof SaludaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/artistas': typeof ArtistasRoute
  '/comercio': typeof ComercioRoute
  '/feria-del-mediodia': typeof FeriaDelMediodiaRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
  '/informacion': typeof InformacionRoute
  '/objetos-perdidos': typeof ObjetosPerdidosRoute
  '/pregonera': typeof PregoneraRoute
  '/prensa': typeof PrensaRoute
  '/programa': typeof ProgramaRoute
  '/que-ver': typeof QueVerRoute
  '/recuerdo': typeof RecuerdoRoute
  '/reinas': typeof ReinasRoute
  '/saluda': typeof SaludaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/artistas': typeof ArtistasRoute
  '/comercio': typeof ComercioRoute
  '/feria-del-mediodia': typeof FeriaDelMediodiaRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
  '/informacion': typeof InformacionRoute
  '/objetos-perdidos': typeof ObjetosPerdidosRoute
  '/pregonera': typeof PregoneraRoute
  '/prensa': typeof PrensaRoute
  '/programa': typeof ProgramaRoute
  '/que-ver': typeof QueVerRoute
  '/recuerdo': typeof RecuerdoRoute
  '/reinas': typeof ReinasRoute
  '/saluda': typeof SaludaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividades'
    | '/artistas'
    | '/comercio'
    | '/feria-del-mediodia'
    | '/galeria'
    | '/historia'
    | '/informacion'
    | '/objetos-perdidos'
    | '/pregonera'
    | '/prensa'
    | '/programa'
    | '/que-ver'
    | '/recuerdo'
    | '/reinas'
    | '/saluda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividades'
    | '/artistas'
    | '/comercio'
    | '/feria-del-mediodia'
    | '/galeria'
    | '/historia'
    | '/informacion'
    | '/objetos-perdidos'
    | '/pregonera'
    | '/prensa'
    | '/programa'
    | '/que-ver'
    | '/recuerdo'
    | '/reinas'
    | '/saluda'
  id:
    | '__root__'
    | '/'
    | '/actividades'
    | '/artistas'
    | '/comercio'
    | '/feria-del-mediodia'
    | '/galeria'
    | '/historia'
    | '/informacion'
    | '/objetos-perdidos'
    | '/pregonera'
    | '/prensa'
    | '/programa'
    | '/que-ver'
    | '/recuerdo'
    | '/reinas'
    | '/saluda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadesRoute: typeof ActividadesRoute
  ArtistasRoute: typeof ArtistasRoute
  ComercioRoute: typeof ComercioRoute
  FeriaDelMediodiaRoute: typeof FeriaDelMediodiaRoute
  GaleriaRoute: typeof GaleriaRoute
  HistoriaRoute: typeof HistoriaRoute
  InformacionRoute: typeof InformacionRoute
  ObjetosPerdidosRoute: typeof ObjetosPerdidosRoute
  PregoneraRoute: typeof PregoneraRoute
  PrensaRoute: typeof PrensaRoute
  ProgramaRoute: typeof ProgramaRoute
  QueVerRoute: typeof QueVerRoute
  RecuerdoRoute: typeof RecuerdoRoute
  ReinasRoute: typeof ReinasRoute
  SaludaRoute: typeof SaludaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividades': {
      id: '/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof ActividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas': {
      id: '/artistas'
      path: '/artistas'
      fullPath: '/artistas'
      preLoaderRoute: typeof ArtistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercio': {
      id: '/comercio'
      path: '/comercio'
      fullPath: '/comercio'
      preLoaderRoute: typeof ComercioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feria-del-mediodia': {
      id: '/feria-del-mediodia'
      path: '/feria-del-mediodia'
      fullPath: '/feria-del-mediodia'
      preLoaderRoute: typeof FeriaDelMediodiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informacion': {
      id: '/informacion'
      path: '/informacion'
      fullPath: '/informacion'
      preLoaderRoute: typeof InformacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetos-perdidos': {
      id: '/objetos-perdidos'
      path: '/objetos-perdidos'
      fullPath: '/objetos-perdidos'
      preLoaderRoute: typeof ObjetosPerdidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pregonera': {
      id: '/pregonera'
      path: '/pregonera'
      fullPath: '/pregonera'
      preLoaderRoute: typeof PregoneraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prensa': {
      id: '/prensa'
      path: '/prensa'
      fullPath: '/prensa'
      preLoaderRoute: typeof PrensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa': {
      id: '/programa'
      path: '/programa'
      fullPath: '/programa'
      preLoaderRoute: typeof ProgramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/que-ver': {
      id: '/que-ver'
      path: '/que-ver'
      fullPath: '/que-ver'
      preLoaderRoute: typeof QueVerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuerdo': {
      id: '/recuerdo'
      path: '/recuerdo'
      fullPath: '/recuerdo'
      preLoaderRoute: typeof RecuerdoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinas': {
      id: '/reinas'
      path: '/reinas'
      fullPath: '/reinas'
      preLoaderRoute: typeof ReinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saluda': {
      id: '/saluda'
      path: '/saluda'
      fullPath: '/saluda'
      preLoaderRoute: typeof SaludaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadesRoute: ActividadesRoute,
  ArtistasRoute: ArtistasRoute,
  ComercioRoute: ComercioRoute,
  FeriaDelMediodiaRoute: FeriaDelMediodiaRoute,
  GaleriaRoute: GaleriaRoute,
  HistoriaRoute: HistoriaRoute,
  InformacionRoute: InformacionRoute,
  ObjetosPerdidosRoute: ObjetosPerdidosRoute,
  PregoneraRoute: PregoneraRoute,
  PrensaRoute: PrensaRoute,
  ProgramaRoute: ProgramaRoute,
  QueVerRoute: QueVerRoute,
  RecuerdoRoute: RecuerdoRoute,
  ReinasRoute: ReinasRoute,
  SaludaRoute: SaludaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
